server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springDemo
    hikari:
      schema: microservices
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      globally_quoted_identifiers: true
      ddl-auto: update
      show-sql: false
  application:
    name: RATING-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
